#!/usr/bin/python
# -*- coding: utf-8 -*-

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)
CARD_WIDTH = int(SCREEN_WIDTH / 5.12)
CARD_HEIGHT = int(SCREEN_HEIGHT / 2.4)
PREV_WIDTH = int(SCREEN_WIDTH / 8.53)
PREV_HEIGHT = int(SCREEN_HEIGHT / 5.95)
SMALL_WIDTH = int(SCREEN_WIDTH / 8.53)
SMALL_HEIGHT = int(SCREEN_HEIGHT / 18.73)
ICON_WIDTH = int(SCREEN_WIDTH / 20.48)
ICON_HEIGHT = ICON_WIDTH
HAND_DRAW_X = 15
HAND_DRAW_Y = (SCREEN_HEIGHT - 15) - PREV_HEIGHT
BOARD_DRAW_X = 15
BOARD_DRAW_Y = (SCREEN_HEIGHT - 30) - PREV_HEIGHT * 2
SCROLL_SPEED = 8

HOVER_TIME = 60
